import React from 'react'
import Ap from '../../Ap';
import { FaArrowRight, FaPeriscope, FaStaylinked, FaPlus } from "react-icons/fa";
import {Accordion} from "react-bootstrap";

export default function Home() {

  const cats = [
    {id: 1, img: 'logo16.png'},
    {id: 2, img: 'logo20.png'},
    {id: 3, img: 'logo18.png'},
    {id: 4, img: 'logo19.png'},
  ];

  const faq = [
    {title: 'What is the Gutter Cat Gang?', icon: <FaPlus className='faq-icon'/>, desc: 'The Gutter Cat Gang is a collection of 3000 unique Gutter Cat NFTs who live in the post-apocalyptic shatters of society on the ETH blockchain. Ownership includes creative & commercial rights of your Gutter Cat as well as initiation into the Gang.'},
    {title: 'How can I join the DAO?', icon: <FaPlus className='faq-icon'/>, desc: 'To enter the DAO you must hold at least one Gutter Cat in your wallet. Gutter Cats can be found for sale on nearly all NFT secondary markets, with most being predominantly on OpenSea.'},
    {title: 'How were the Gutter Cats created?', icon: <FaPlus className='faq-icon'/>, desc: 'Each Gutter Cat is algorithmically generated by combining 123 properties with varying rarities in nine categories (Furs, Backgrounds, Eyes, Mouths, Shirts, Hats, Earrings, Necklaces, & Beards).'},
    {title: "What's the Gutter Cat Gang's origin?", icon: <FaPlus className='faq-icon'/>, desc: 'The year is 2050. Humans are an interplanetary species & have all but abandoned the post-apocalyptic shatters of society on earth. Cats have taken over. One crime-ridden, nondescript inner city is inhabited by a group of cats collectively known as the Gutter Cats. This is their story.'},
  ]

  return (
    <article className="container-fluid mt-5 ">
      <div className="row mt-2 mb-5 align-items-center px-md-5">
        <div className="col-11 mx-auto col-md-12 col-lg-6">
          <h1 className='title'>A <span className='image-text' style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}}>NEW ERA</span> OF NFT UTILITY</h1>
          <p className='paragraphs'>The Gutter Cat Gang DAO exists to transcend the potential of the Gang beyond that of your standard NFT community or club. The Gang survived an apocalypse and lived to tell the story of the Gutter DAO’s emergence from a collective of social network accounts and channels that transformed into a fully operational community run organization under the guise of the Gutter Cat Gang members.</p>
          <a href="https://www.gcgdao.info/news/dao-powered-nft-communities">
            <div className="hero-btn py-3 my-5">
              Our DAO Article
            </div>
          </a>
          <div className="row pt-3 d-none d-lg-flex">
            <div className='col-5 mx-auto'>
              <div>
                <FaPeriscope className='icon mb-3'/>
              </div>
              <h6 className='text-white'><b>Organic Autonomy</b></h6>
              <p className="paragraphs">Our DAO fosters influential synergies, resulting in a self-sustaining engine of innovation for the future.</p>
            </div>
            <div className="col-2 mx-auto">
              <div className="timeline"></div>
            </div>
            <div className='col-5 mx-auto'>
              <div>
                <FaStaylinked className='icon mb-3'/>
              </div>
              <h6 className='text-white'><b>On-chain Governanc</b></h6>
              <p className="paragraphs">wnership of a Gutter Cat gives members the ability to vote on certain topics, such as community project initiatives and endeavors.</p>
            </div>
          </div>
        </div>
        <div className="col-11 col-md-12 col-lg-6 mx-auto">
          <Ap/>
        </div>
        <div className="row pt-3 d-lg-none p-md-0">
            <div className='col-11 col-sm-5 mx-auto mb-4 mb-sm-0'>
              <div>
                <FaPeriscope className='icon mb-3'/>
              </div>
              <h6 className='text-white'><b>Organic Autonomy</b></h6>
              <p className="paragraphs">Our DAO fosters influential synergies, resulting in a self-sustaining engine of innovation for the future.</p>
            </div>
            <hr className='d-sm-none'/>
            <div className="col-2 d-none d-sm-block mx-auto">
              <div className="timeline"></div>
            </div>
            <div className='col-11 col-sm-5 mx-auto mb-4 mb-sm-0'>
              <div>
                <FaStaylinked className='icon mb-3'/>
              </div>
              <h6 className='text-white'><b>On-chain Governanc</b></h6>
              <p className="paragraphs" id='dao'>wnership of a Gutter Cat gives members the ability to vote on certain topics, such as community project initiatives and endeavors.</p>
            </div>
          </div>
      </div >
      <hr id='dao'/>
        <h1 className="title mt-5 pt-5 my-4 px-4 px-md-5">WHAT IS A <span style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} className="image-text">DAO</span>?</h1>
      <div className="row px-4 px-md-5 align-items-center">
        <div className="col-12 col-lg-6 mt-4">
        
          <div style={{width: '15%'}} className='my-3'>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" width="1000" height="1000" preserveAspectRatio="xMidYMid meet"style={{width: '100%', height: '100%', transform: 'translate3d(0px, 0px, 0px)'}}>
            <defs>
              <clipPath id="__lottie_element_21">
                <rect width="1000" height="1000" x="0" y="0"></rect>
              </clipPath>
              <image href='../../../logo11.png'></image>
              <image href='../../../logo10.png'></image>
            </defs>
            <g clip-path="url(#__lottie_element_21)">
              <g class="png" transform="matrix(1,0,0,1,0,0)" opacity="1" style={{display: "block"}}>
                <image href='../../../logo10.png' width="1000px" height="1000px" preserveAspectRatio="xMidYMid slice"></image>
              </g>
              <g class="png3" opacity="1" style={{display: 'block'}}>
                <image href='../../../logo11.png' width="480px" height="480px" className='' preserveAspectRatio="xMidYMid slice"></image>
              </g>
            </g>
          </svg>
          </div>
          <h1 className="sub-title" style={{wordBreak: 'break-word'}}>NEXT  STEP IN ORGANIZATIONAL STRUCTURE AND GOVERNANCE</h1>
          <div className="paragraphs">
            They allow for a decentralized, fair system of decision-making without any hierarchy or centralized power that control all aspects of an organization's operation from top to bottom.
          </div>
          <div className="row">
            <div className="col-2 col-sm-3">
              <div className="x-timeline mx-auto mt-2"></div>
            </div>
            <div className="col-10 col-sm-9 mx-auto">
              <div className="paragraphs">
                This allows for true equality amongst our gang. Empowering every Gutter Cat Gang holder with not only membership, but voting power. Each will play a key role in determining the direction our community will take.
              </div>
            </div>
          </div>
        </div>
        <div className="col-12 order-lg-first col-lg-6 mx-auto">
          <img src="../../../logo12.png" className="w-100" alt="" />
        </div>
      </div>
      <hr />
      <div className="scroll px-0">
        <div style={{backgroundImage: 'url(../../../logo13.png)'}} className='scroll-1 pb-0 mb-5'>scroll 1</div>
        <div style={{backgroundImage: 'url(../../../logo14.png)'}} className='scroll-2'>scroll 1</div>
      </div>
      <hr id='cat'/>
      <div className="row mx-auto text-center my-5">
        <div className="col-11 col-md-6 mx-auto my-3">
          <h4 className="sub-title my-3">CATS FOR <span style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} className="image-text">ADOPTION</span></h4>
          <div className="paragraphs">View some of the most recently listed Gutter Cat Gang members that have been put up for adoption on secondary markets.</div>
          <a href='https://opensea.io/collection/guttercatgang'>
            <div className="hero-btn py-3 my-2 mx-auto">
              See All <FaArrowRight/>
            </div>
          </a>
        </div>
      </div>
      <div className="row mb-5">
        {cats.map(({id, img})=>{
          return (
            <div key={id} className="col-6 col-md-3 mx-auto">
              <img src={img} alt="" className="w-100 mx-auto mt-2" />
            </div>
          )
        })}
      </div>
      <div className="row my-5 py-5 d-none">
        <div className="col-10 col-md-6">
          <div className="circle-1">
            <div className='div px-3 mx-1 my-2'>
              <div>
                <h5>
                  <b className="text-white">
                  LEGALLY-GUTTERED DAO
                  </b>
                </h5>
                <div className="paragraphs">Gutter Labs is our soul-wrapper and the real-world legal entity that interacts with existing companies and brands on behalf of us, Gutter Cat Gang DAO. This enables us to go further than the metaverse and ensure real world operations.
              </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-11 col-md-6">
          <div className="positon-relative">
            <h1 className="title">KEY ELEMENTS
            OF <span style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} className="image-text">OUR DAO</span></h1>
            <div className="circle-2 ">
            <div className='div2 px-3 mx-1 my-2'>
              <div>
                <h5>
                  <b className="text-white">
                  D-DAY FOR THE GUTTER
                  </b>
                </h5>
                <p className="paragraphs">In our early stages, the contract will be more controlled and easily updated. In later stages, the control over the contract will be incrementally released at an increasing rate until 100% decentralization is reached.</p>
              </div>
            </div>
          </div>
          </div> 
        </div>
        <div className="col-11 col-md-6 col-lg-6 my-3">
          <div className="circle-1 mx-auto">
            <div className='div px-3 mx-1 my-2'>
              <div>
                <h5>
                  <b className="text-white">
                  LEGALLY-GUTTERED DAO
                  </b>
                </h5>
                <div className="paragraphs">Gutter Labs is our soul-wrapper and the real-world legal entity that interacts with existing companies and brands on behalf of us, Gutter Cat Gang DAO. This enables us to go further than the metaverse and ensure real world operations.
              </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-11 col-md-6 col-lg-6">
          <div className="circle-1 mx-auto">
            <div className='div px-3 mx-1 my-2'>
              <div>
                <h5>
                  <b className="text-white">
                  LEGALLY-GUTTERED DAO
                  </b>
                </h5>
                <div className="paragraphs">Gutter Labs is our soul-wrapper and the real-world legal entity that interacts with existing companies and brands on behalf of us, Gutter Cat Gang DAO. This enables us to go further than the metaverse and ensure real world operations.
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr />
      <div className="row mx-1 my-5 py-5">
        <h4 className="text mb-0">FAQ</h4>
        <h className="title">GET THE <span style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} className="image-text">FACTS</span></h>
        {faq.map(({title, desc, icon}, index)=>{
          return (
            <div key={index}>
              <Faq title={title} desc={desc} icon={icon} index={index}/>
            </div>
          )
        })}
        <hr />
      </div>
      <div className="row mx-0 px-0">
        <div className="col-12 col-md-6 mx-0 px-0">
          <div className="video-container">
            <video src="../../../video.mp4" className='video' autoPlay={'autoplay'} loop preload='auto'></video>
          </div>
        </div>
        <div className="col-12 col-md-6 my-5 px-3">
          <h4 className="text-muted">Community Opportunities</h4>
          <h1 className="title">EXPLORE <span className="image-text" style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} >LEADERSHIP</span> ROLES AND HELP US LEAD THE <span className="image-text" style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} >FUTURE</span>.</h1>
          <a href="https://guttercatgangdao.typeform.com/to/pTbgVlCi">
          <div className="hero-btn py-3 my-5">
            Register Now <FaArrowRight/>
          </div>
          </a>
        </div>
      </div>
      <hr />
      <div style={{height: '100%'}} className="row my-5 py-4">
        <div className="col-8 col-md-4 mb-3">
          <img src="../../../svg6.png" alt="" className="w-100 rounded align-self-start" />
        </div>
        <div className="col-11 col-md-8 mt-4 align-self-center">
          <div className='align-self-center instagram-container d-none d-md-block text-center'>
            <p className='paragraphs mx-3'><b>Follow us on Instagram</b></p>
            <h1 className="title pt-0 mt-0 instagram"><a href='https://www.instagram.com/guttercatgang_/' className="image-text" style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} >INSTAGRAM</a></h1>
          </div>
          <p className='paragraphs mx-3 d-md-none'><b>Follow us on Instagram</b></p>
            <h1 className="title pt-0 mt-0 d-md-none"><span className="image-text" style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} >INSTAGRAM</span></h1>
        </div>
        <div className="col-8 col-md-4 mt-4 align-self-end mx-auto">
          <div className='align-self-end position-relative'>
            <img src="../../../svg7.png" alt="" className="w-100 rounded" />
            <a href="https://www.instagram.com/guttercatgang_/">
              <img src="../../../logo21.png" alt="" className="w-25 position-absolute top-0 translate-middle border border-light rounded-circle" />
            </a>
          </div>
        </div>
      </div>
      <br />
      <hr />
      <div className="row my-5 py-5">
        <div className="col-11 col-md-9 col-lg-6">
          <h6 className='timeline-text'><b>Have a unique idea you want to pitch to the DAO?</b></h6>
          <h1 className="title mt-0 pb-0">
            <span style={{backgroundImage: 'url(../../../logo.svg) ,linear-gradient(139deg, #ec9228, #b547f9)'}} className="image-text">GET IN TOUCH</span>
          </h1>
          <div className="b-bottom mx-2"></div>
        </div>
      </div>
      <hr />
      <footer>
        <div className="d-md-flex d-block justify-content-around align-items-center py-3">
          <div> 
            <img className='my-2 mx-2' src="../../../logo.svg" alt="" />
          </div>
          <h5 className='my-2 mx-2 text-muted footer-link'>HOME</h5>
          <h5 className='my-2 mx-2 text-muted footer-link'>THE DAO</h5>
          <h5 className='my-2 mx-2 text-muted footer-link'>ADOPT CAT</h5>
          <h5 className='my-2 mx-2 text-muted footer-link'>DAO ELEMENTS</h5>
        </div>
        <hr />
      </footer>
    </article>
  )
}

const Faq = ({title, desc, index}) =>{
  return (
    <div className='col-12 py-5 border-bottom' key={index}>
      <Accordion defaultActiveKey={index} flush>
        <Accordion.Item eventKey='0'>
          <Accordion.Header>{title}</Accordion.Header>
          <Accordion.Body>{desc}</Accordion.Body>
        </Accordion.Item>
      </Accordion>
    </div>
  )
}